apiVersion: v1
kind: Service
metadata:
  name: tomdemoservice
  labels:
    app: tomdemo
spec:

  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: tomdemo
  type: LoadBalancer