apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.container.name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.container.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.container.name }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image }}:{{ .Values.container.tag }}
          ports:
          - containerPort: {{ .Values.container.port }}
          resources:
            requests:
              memory: "10Mi"
              cpu: "100m"
            limits:
              memory: "20Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /
              port: 8888
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8888
            initialDelaySeconds: 3
            periodSeconds: 3